version: "3"
services:
  test_app:
    image: parsaee/tickets-test
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://db/testdb

  db:
    image: mongo
    ports: 
      - "27020:27017"
