name: tests-payments

on:
  pull_request:
    paths:
      - 'payments/**'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: cd payments && npm install && npm run test:ci
